[config]


# kitty
[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

# hyprland 
[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

# waybar 
[templates.waybar]
input_path = '~/.config/matugen/templates/matugen-waybar.css'
output_path = '~/.config/waybar/matugen/matugen-waybar.css'
post_hook = 'pkill -SIGUSR2 waybar'

# btop
[templates.btop]
input_path = '~/.config/matugen/templates/matugen-btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook =   'pkill -USR2 btop'

# rofi
[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

# gtk3
[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

# gtk4
[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

# Cava
[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/config'
post_hook =   'pkill -USR1 cava'

# swaync 
[templates.swaync]
input_path = '~/.config/matugen/templates/matugen-swaync.css'
output_path = '~/.config/swaync/matugen/matugen-swaync.css'
post_hook = 'swaync-client -rs'


[templates.nvim]
input_path = '~/.config/nvim/pywal/matugen.lua'
output_path = '~/.cache/wal/base46-dark.lua'

[templates.nvimlight]
input_path = '~/.config/nvim/pywal/matugen.lua'
output_path = '~/.cache/wal/base46-light.lua'

[templates.pywal]
input_path = '~/.config/nvim/pywal/waltemplate'
output_path = '~/.cache/wal/colors'

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true

#--------end-of-nvim-colors---------

#-------------full-bar-----------------
[templates.fullbar]
input_path = '~/.config/matugen/templates/matugen-waybar.css'
output_path = '~/.local/bin/moonbar/styles/colors.css'
post_hook    =   'pkill -9 "ax-shell"' 
#---------------bar-end----------------
